### ISSUE TITLE
Suggestion: Shop

### ISSUE THREAD

**Issue by michaelrosstarr** [Pliexe/discord-money-mongoose#1]
A built in way for users to spend their well earned cash

**Comment by Pliexe** [comment]
Noted! It seems like an interesting idea but not sure how to implement it. Or maybe I could make that into a separate module which maybe could be more convenient, If you have an idea on in what way would it be nice to implement it you can give an idea. I will keep this thread open to give you chance if you want to respond!

**Comment by Pliexe** [comment]
Actually I decided how I will go with it, I will make this into a separate module.
